version: '3.8'

services:
  mysql-shop:
    image: mysql:8.0
    container_name: mysql-sage
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: Member
    ports:
      - "3016:3306"
    volumes:
      - ./mysql-bank-a-data:/var/lib/mysql
      - ./init-Balance.sql:/docker-entrypoint-initdb.d/init-Balance.sql
      - ./init-Log.sql:/docker-entrypoint-initdb.d/init-Log.sql
      - ./init-Member.sql:/docker-entrypoint-initdb.d/init-Member.sql
    command: --default-authentication-plugin=mysql_native_password
            --innodb_lock_wait_timeout=120
            --max_connections=1000
    networks:
      - saga-network


networks:
  saga-network:
    driver: bridge